version: "2.14.2"
name: polyas-verifier
services:
 vite_docker:
   build:
    context: .
    dockerfile: Dockerfile
    args:
      DIR: /srv/app
      NAME: polyas-verifier
   container_name: polyas-verifier
   entrypoint:
     - /usr/local/bin/npm
     - run
     - dev
   environment:
     VITE_BACKEND: http://localhost:5000
     VITE_FINGERPRINT: 10
     VITE_MODE: deploy
     VITE_INSTANCE: https://election.polyas.com
   image: node:alpine
   networks:
     - kastel
   ports:
     - mode: host
       target: 5000
       published: "5000"
       protocol: tcp
   restart: always
   tty: true
   working_dir: /srv/app/polyas-verifier
networks:
  kastel:
    name: polyas-verifier
