version: "2.14.2"
services:
 vite_docker:
   image: node:alpine
   environment:
      VITE_MODE: deploy
      VITE_BACKEND: http://localhost:5000
      VITE_FINGERPRINT: 10
   container_name: polyas-verifier
   restart: always
   entrypoint: [/usr/local/bin/npm, run, dev]
   ports:
     - 5000:5000
   working_dir: /srv/app/polyas-verifier
   build:
    context: .
    dockerfile: Dockerfile
    args:
      NAME: polyas-verifier
      DIR: /srv/app
   tty: true
