version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DIR: /home/local/gi-wahlverifikation
        NAME: polyas-verifier
    container_name: polyas-verifier
    args:
      DIR: /home/local/gi-wahlverifikation/polyas-verifier
      NAME: polyas-verifier
      ELECTION_URL: https://election.polyas.com
      ELECTION_HASH: a1d0c6e8-3f02-7327-d846-1063f4Ac58a6
      ELECTION_FINGERPRINT: 42
      ELECTION_BACKEND: http://localhost:5000
    extra_hosts:
      127.0.0.1: host-gateway
    image: node:alpine
    ports:
    - mode: host
      target: 5000
      published: "5000"
      protocol: tcp
    restart: always
    tty: true
    working_dir: /home/local/gi-wahlverifikation/polyas-verifier
