version: "2.14.2"
name: polyas-verifier
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DIR: /srv/app
        NAME: polyas-verifier
      network: host
    container_name: polyas-verifier
    entrypoint:
    - /usr/local/bin/npm
    - run
    - dev
    environment:
      ELECTION_URL: https://election.polyas.com
      ELECTION_FINGERPRINT: 42
      ELECTION_BACKEND: http://localhost:5000
      ELECTION_MODE: deploy
    image: node:alpine
    network_mode: bridge
    ports:
    - mode: host
      target: 5000
      published: "5000"
      protocol: tcp
    restart: always
    tty: true
    working_dir: /srv/app/polyas-verifier
networks:
  default:
    driver: bridge
    external: true
