version: "2.14.2"
services:
 vite_docker:
   image: node:alpine
   environment:
      VITE_MODE: deploy
      VITE_BACKEND: http://localhost:5000
      VITE_FINGERPRINT: 1
   container_name: polyas-verifier
   ports:
     - 5000
   working_dir: /srv/app/polyas-verifier
   build:
    context: .
    dockerfile: Dockerfile
   tty: true
