version: "3.4"
services:
 vite_docker:
   image: node:alpine
   environment:
      VITE_MODE: deploy
      VITE_BACKEND: http://localhost
      VITE_FINGERPRINT: 1
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - 8080:4300
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
